# -*- coding: utf-8 -*-
"""patokenizer-2026-502.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rvwxRBuFEsmrTLnOvXXG2o3qNHvLa2Wf
"""

import re

# Estes es el patron
pattern = r"^[a-zA-Z]\w*\b"

# Ejemplo sin match
text2 = "12aa123"
match2 = re.match(pattern, text2)
print(match2)

# Ejemplo de match
text1 = "abcd_123 blah bla cosas"
match1 = re.match(pattern, text1)

print(match1)  # imprimir el amtch muestra un objeto

print(match1.group(), len(match1.group()) )  #match group es la subcadena

class Tokenizer:
  tokens = []             #   el token stream
  regex_table = {}        #   un diccionario de expresiones regulares
  keyword_list = []       #   una lista de keywords

  # El objeto token deberia ser inicializado con.... ?
  #     el diccionario de expresiones
  #     la lista de keywords
  def __init__(self, param1, param2 ) :
    self.regex_table = param1
    self.keyword_list = param2
    self.tokens = []

  # Busca el match mas largo
  def longest_match(self,  input_string):
    # Por cada label en el diccionario de regex
      # Revisa si produce un match
        # De ser asi, agrega el label y matching substring a una lista de matche.s
    matches = []

    for i in self.regex_table:
        regex = self.regex_table[i]
        label = i
        match1 = re.match(regex, input_string)
        if match1:
            token = [label,match1.group()]
            if match1.group() in self.keyword_list:
                token[0] = "kw_" + match1.group()

            matches.append(token)

    if matches:
        best_match = max(matches, key = lambda x: len(x[1]))
        return best_match
    else:
        return None

    #print(matches)


    # Si no hubo ningun match, devuelve None

    # Si hay matches, encuentra el mas largo
    # Si el match resulta ser una keyword, cambia su label acorde

    # Devuelve el best_match


  # Recibe la cadena a tokenizar
  # Devuelve el stream de tokens
  def tokenize(self, input_string ):

    while input_string:
        # El ciclo del algoritmo:
        # Mientras el input_string tenga caracteres...
        # Remueve blanks al inicio de input_string, con strip
        input_string = input_string.strip()



      # Si input_string no quedo vacio:
        if input_string:
            token = self.longest_match(input_string)

            if token:
                self.tokens.append(token)
                longitud = len(token[1])
                input_string = input_string[longitud:]
            else:
                print("Error")
                break

        #   Busca el matching substring mas largo a partir del inicio de input_substring

        #   Si hubo un match:
          # Agrega el match a la lista de tokens
          # Remueve el matching substring al inicio de input_string

        #   Si no: Error!!

    # Devuelve la lista de tokens
    return self.tokens

dictio_regex = { 'const_int' : r"^[0-9]+\b",
				'identifier' : r"^[a-zA-Z]\w*\b",
				'=' : r"^=",
				'semicol' : r"^;",
                 '+' : r"^\+",
                 '(' : r"^\(",
                 ')' : r"^\)"
      }

keyword_list = ["print" ]

input_program = """
    value = 45 + 10;
    print(a);
"""

# Crea el objeto tokenizer
#patokenizer = Tokenizer (dictio_regex, keyword_list)
# Tokeniza input_program
patokenizer =  Tokenizer(dictio_regex, keyword_list )

# Salida esperada: el stream de tokens por linea,
# y la tabla de simbolos

tokens = patokenizer.tokenize(input_program)
print(input_program, "\n")

for tok in tokens:
    print(tok)